/**
 * TypeScript types that match the REDLINK Supabase PostgreSQL schema exactly.
 *
 * These are separate from src/lib/types.ts (which contains the original
 * speculative application-layer types). The two will be unified when
 * frontend forms are connected to the database in a future step.
 */

// ---------------------------------------------------------------------------
// Enum value types (match CHECK constraints in the database)
// ---------------------------------------------------------------------------

/** Valid blood groups — matches the CHECK constraint on donors.blood_group and requests.blood_group */
export type DbBloodGroup = 'A+' | 'A-' | 'B+' | 'B-' | 'AB+' | 'AB-' | 'O+' | 'O-';

/** Valid urgency levels — matches the CHECK constraint on requests.urgency */
export type DbUrgency = 'urgent' | 'normal';

/** Valid request statuses — matches the CHECK constraint on requests.status */
export type DbRequestStatus = 'pending' | 'matched' | 'accepted' | 'completed' | 'cancelled';

/** Valid match types — matches the CHECK constraint on matches.match_type */
export type DbMatchType = 'exact' | 'compatible';

/** Valid match statuses — matches the CHECK constraint on matches.match_status */
export type DbMatchStatus = 'pending' | 'accepted' | 'declined';

// ---------------------------------------------------------------------------
// Row types (match table columns exactly)
// ---------------------------------------------------------------------------

/** Row shape for the `donors` table */
export interface DbDonor {
  id: string;              // uuid, PK
  name: string;            // text, NOT NULL
  blood_group: DbBloodGroup;
  locality: string;        // text, NOT NULL
  pincode: string;         // text, NOT NULL
  last_donation_date: string; // date (ISO 'YYYY-MM-DD'), NOT NULL
  phone: string;           // text, NOT NULL — PRIVATE until match acceptance
  created_at: string;      // timestamptz, NOT NULL, DEFAULT now()
}

/** Row shape for the `requests` table */
export interface DbRequest {
  id: string;              // uuid, PK
  requester_name: string;  // text, NOT NULL
  blood_group: DbBloodGroup;
  locality: string;        // text, NOT NULL
  pincode: string;         // text, NOT NULL
  hospital: string;        // text, NOT NULL
  urgency: DbUrgency;
  phone: string;           // text, NOT NULL — PRIVATE until donor accepts
  status: DbRequestStatus;
  created_at: string;      // timestamptz, NOT NULL, DEFAULT now()
}

/** Row shape for the `matches` table */
export interface DbMatch {
  id: string;              // uuid, PK
  request_id: string;      // uuid, FK → requests.id
  donor_id: string;        // uuid, FK → donors.id
  match_type: DbMatchType;
  match_status: DbMatchStatus;
  matched_at: string;      // timestamptz, NOT NULL, DEFAULT now()
  accepted_at: string | null; // timestamptz, nullable
}

// ---------------------------------------------------------------------------
// Insert types (omit server-generated columns)
// ---------------------------------------------------------------------------

/** Payload for inserting a new donor (id, created_at generated by DB) */
export type DbDonorInsert = Omit<DbDonor, 'id' | 'created_at'>;

/** Payload for inserting a new request (id, created_at, status generated by DB) */
export type DbRequestInsert = Omit<DbRequest, 'id' | 'created_at' | 'status'>;

/** Payload for inserting a new match (id, matched_at, accepted_at generated/nullable) */
export type DbMatchInsert = Omit<DbMatch, 'id' | 'matched_at' | 'accepted_at'>;
